// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// These two values are PUBLIC by design. Vite inlines them into the client
// bundle at build time, so they are already visible to every visitor — the
// anon key grants no privileged access and every table is protected by RLS.
//
// They are hardcoded as fallbacks deliberately: the build used to depend on a
// committed .env, so removing that file from version control produced a bundle
// with `undefined` config. createClient() then threw during module init and the
// app never mounted — users saw a blank page. Env vars still take precedence,
// so other environments can point at a different project.
const FALLBACK_SUPABASE_URL = 'https://zbkjbbujsdlpujotgltm.supabase.co';
const FALLBACK_SUPABASE_PUBLISHABLE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpia2piYnVqc2RscHVqb3RnbHRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMyMjE1NTUsImV4cCI6MjA4ODc5NzU1NX0.lcuURVZZ4aMm_wBK1ry5dlo_cxYUMvjaKPcE_9LMpeA';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || FALLBACK_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || FALLBACK_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});